### ISSUE TITLE
Commenting out the whole code after //

### ISSUE THREAD

**Issue by hugotiburtino** [ceylanb/firefox-js-beautifier#1]
Hi there, 
19 days and this project has already a fan. Hope it goes on.
I have the following issue: 
If you open js file like this:
http://web.mit.edu/mprat/Public/web/Terminus/Web/static/javascript/Game.js
You can see that the whole code after a comment with '//' is commented out.

(Here a [screenshot](https://firefox-js-beautifier-isssue1.s3.eu-central-1.amazonaws.com/Screenshot+from+2020-05-20+14-01-39.png))

**Comment by hugotiburtino** [comment]
Ok, I figured out the problem and fixed it. See pull request

**Comment by ceylanb** [comment]
Thanks for your nice contribution. I merged the patch and published the new version with the new style on Firefox Add-Ons.
